/* eslint-disable */
// Auto-generated by Supabase CLI — do not edit manually
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      action_plan_evidence: {
        Row: {
          action_plan_id: number
          file_name: string
          file_size: number | null
          file_type: string | null
          id: number
          storage_path: string
          storage_url: string | null
          tenant_id: string | null
          update_id: number | null
          uploaded_at: string | null
          uploaded_by: string | null
        }
        Insert: {
          action_plan_id: number
          file_name: string
          file_size?: number | null
          file_type?: string | null
          id?: number
          storage_path: string
          storage_url?: string | null
          tenant_id?: string | null
          update_id?: number | null
          uploaded_at?: string | null
          uploaded_by?: string | null
        }
        Update: {
          action_plan_id?: number
          file_name?: string
          file_size?: number | null
          file_type?: string | null
          id?: number
          storage_path?: string
          storage_url?: string | null
          tenant_id?: string | null
          update_id?: number | null
          uploaded_at?: string | null
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "action_plan_evidence_action_plan_id_fkey"
            columns: ["action_plan_id"]
            isOneToOne: false
            referencedRelation: "action_plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plan_evidence_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plan_evidence_update_id_fkey"
            columns: ["update_id"]
            isOneToOne: false
            referencedRelation: "action_plan_updates"
            referencedColumns: ["id"]
          },
        ]
      }
      action_plan_stores: {
        Row: {
          action_plan_id: number
          created_at: string | null
          id: number
          store_id: number
          tenant_id: string | null
        }
        Insert: {
          action_plan_id: number
          created_at?: string | null
          id?: number
          store_id: number
          tenant_id?: string | null
        }
        Update: {
          action_plan_id?: number
          created_at?: string | null
          id?: number
          store_id?: number
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "action_plan_stores_action_plan_id_fkey"
            columns: ["action_plan_id"]
            isOneToOne: false
            referencedRelation: "action_plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plan_stores_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plan_stores_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      action_plan_updates: {
        Row: {
          action_plan_id: number
          content: string | null
          created_at: string | null
          id: number
          new_status: string | null
          old_status: string | null
          tenant_id: string | null
          update_type: string
          user_id: string
        }
        Insert: {
          action_plan_id: number
          content?: string | null
          created_at?: string | null
          id?: number
          new_status?: string | null
          old_status?: string | null
          tenant_id?: string | null
          update_type: string
          user_id: string
        }
        Update: {
          action_plan_id?: number
          content?: string | null
          created_at?: string | null
          id?: number
          new_status?: string | null
          old_status?: string | null
          tenant_id?: string | null
          update_type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "action_plan_updates_action_plan_id_fkey"
            columns: ["action_plan_id"]
            isOneToOne: false
            referencedRelation: "action_plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plan_updates_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      action_plans: {
        Row: {
          assigned_by: string | null
          assigned_function_id: number | null
          assigned_to: string
          checklist_id: number | null
          completed_at: string | null
          created_at: string | null
          created_by: string | null
          deadline: string
          description: string | null
          field_condition_id: number | null
          field_id: number | null
          id: number
          is_reincidencia: boolean
          non_conformity_value: string | null
          parent_action_plan_id: number | null
          reincidencia_count: number
          response_id: number | null
          sector_id: number | null
          severity: string
          started_at: string | null
          status: string
          store_id: number | null
          template_id: number | null
          tenant_id: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          assigned_by?: string | null
          assigned_function_id?: number | null
          assigned_to: string
          checklist_id?: number | null
          completed_at?: string | null
          created_at?: string | null
          created_by?: string | null
          deadline: string
          description?: string | null
          field_condition_id?: number | null
          field_id?: number | null
          id?: number
          is_reincidencia?: boolean
          non_conformity_value?: string | null
          parent_action_plan_id?: number | null
          reincidencia_count?: number
          response_id?: number | null
          sector_id?: number | null
          severity?: string
          started_at?: string | null
          status?: string
          store_id?: number | null
          template_id?: number | null
          tenant_id?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          assigned_by?: string | null
          assigned_function_id?: number | null
          assigned_to?: string
          checklist_id?: number | null
          completed_at?: string | null
          created_at?: string | null
          created_by?: string | null
          deadline?: string
          description?: string | null
          field_condition_id?: number | null
          field_id?: number | null
          id?: number
          is_reincidencia?: boolean
          non_conformity_value?: string | null
          parent_action_plan_id?: number | null
          reincidencia_count?: number
          response_id?: number | null
          sector_id?: number | null
          severity?: string
          started_at?: string | null
          status?: string
          store_id?: number | null
          template_id?: number | null
          tenant_id?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "action_plans_assigned_function_id_fkey"
            columns: ["assigned_function_id"]
            isOneToOne: false
            referencedRelation: "functions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_checklist_id_fkey"
            columns: ["checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_field_condition_id_fkey"
            columns: ["field_condition_id"]
            isOneToOne: false
            referencedRelation: "field_conditions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_field_id_fkey"
            columns: ["field_id"]
            isOneToOne: false
            referencedRelation: "template_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_parent_action_plan_id_fkey"
            columns: ["parent_action_plan_id"]
            isOneToOne: false
            referencedRelation: "action_plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_response_id_fkey"
            columns: ["response_id"]
            isOneToOne: false
            referencedRelation: "checklist_responses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "checklist_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_plans_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      activity_log: {
        Row: {
          action: string
          checklist_id: number | null
          created_at: string | null
          details: Json | null
          id: number
          store_id: number | null
          tenant_id: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          checklist_id?: number | null
          created_at?: string | null
          details?: Json | null
          id?: number
          store_id?: number | null
          tenant_id?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          checklist_id?: number | null
          created_at?: string | null
          details?: Json | null
          id?: number
          store_id?: number | null
          tenant_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_checklist_id_fkey"
            columns: ["checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      app_settings: {
        Row: {
          description: string | null
          key: string
          tenant_id: string | null
          updated_at: string | null
          value: string
        }
        Insert: {
          description?: string | null
          key: string
          tenant_id?: string | null
          updated_at?: string | null
          value: string
        }
        Update: {
          description?: string | null
          key?: string
          tenant_id?: string | null
          updated_at?: string | null
          value?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_settings_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      attachments: {
        Row: {
          file_name: string
          file_size: number | null
          file_type: string | null
          id: number
          response_id: number
          storage_path: string
          storage_provider: string | null
          storage_url: string | null
          tenant_id: string | null
          uploaded_at: string | null
          uploaded_by: string | null
        }
        Insert: {
          file_name: string
          file_size?: number | null
          file_type?: string | null
          id?: number
          response_id: number
          storage_path: string
          storage_provider?: string | null
          storage_url?: string | null
          tenant_id?: string | null
          uploaded_at?: string | null
          uploaded_by?: string | null
        }
        Update: {
          file_name?: string
          file_size?: number | null
          file_type?: string | null
          id?: number
          response_id?: number
          storage_path?: string
          storage_provider?: string | null
          storage_url?: string | null
          tenant_id?: string | null
          uploaded_at?: string | null
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "attachments_response_id_fkey"
            columns: ["response_id"]
            isOneToOne: false
            referencedRelation: "checklist_responses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attachments_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attachments_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          changes: Json | null
          created_at: string | null
          id: string
          ip_address: unknown
          resource_id: string | null
          resource_type: string
          tenant_id: string
          user_id: string | null
        }
        Insert: {
          action: string
          changes?: Json | null
          created_at?: string | null
          id?: string
          ip_address?: unknown
          resource_id?: string | null
          resource_type: string
          tenant_id: string
          user_id?: string | null
        }
        Update: {
          action?: string
          changes?: Json | null
          created_at?: string | null
          id?: string
          ip_address?: unknown
          resource_id?: string | null
          resource_type?: string
          tenant_id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      checklist_justifications: {
        Row: {
          checklist_id: number
          field_id: number
          id: number
          justification_text: string
          justified_at: string | null
          justified_by: string | null
          tenant_id: string | null
        }
        Insert: {
          checklist_id: number
          field_id: number
          id?: number
          justification_text: string
          justified_at?: string | null
          justified_by?: string | null
          tenant_id?: string | null
        }
        Update: {
          checklist_id?: number
          field_id?: number
          id?: number
          justification_text?: string
          justified_at?: string | null
          justified_by?: string | null
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checklist_justifications_checklist_id_fkey"
            columns: ["checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_justifications_field_id_fkey"
            columns: ["field_id"]
            isOneToOne: false
            referencedRelation: "template_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_justifications_justified_by_fkey"
            columns: ["justified_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_justifications_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      checklist_responses: {
        Row: {
          answered_at: string | null
          answered_by: string | null
          checklist_id: number
          field_id: number
          id: number
          tenant_id: string | null
          value_json: Json | null
          value_number: number | null
          value_text: string | null
        }
        Insert: {
          answered_at?: string | null
          answered_by?: string | null
          checklist_id: number
          field_id: number
          id?: number
          tenant_id?: string | null
          value_json?: Json | null
          value_number?: number | null
          value_text?: string | null
        }
        Update: {
          answered_at?: string | null
          answered_by?: string | null
          checklist_id?: number
          field_id?: number
          id?: number
          tenant_id?: string | null
          value_json?: Json | null
          value_number?: number | null
          value_text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checklist_responses_answered_by_fkey"
            columns: ["answered_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_responses_checklist_id_fkey"
            columns: ["checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_responses_field_id_fkey"
            columns: ["field_id"]
            isOneToOne: false
            referencedRelation: "template_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_responses_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      checklist_sections: {
        Row: {
          checklist_id: number
          completed_at: string | null
          id: number
          section_id: number
          status: string
          tenant_id: string | null
        }
        Insert: {
          checklist_id: number
          completed_at?: string | null
          id?: number
          section_id: number
          status?: string
          tenant_id?: string | null
        }
        Update: {
          checklist_id?: number
          completed_at?: string | null
          id?: number
          section_id?: number
          status?: string
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checklist_sections_checklist_id_fkey"
            columns: ["checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_sections_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "template_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_sections_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      checklist_templates: {
        Row: {
          admin_only: boolean | null
          allowed_end_time: string | null
          allowed_start_time: string | null
          category: string | null
          created_at: string | null
          created_by: string | null
          description: string | null
          id: number
          is_active: boolean | null
          justification_deadline_hours: number | null
          name: string
          skip_justifications: boolean | null
          tenant_id: string | null
          updated_at: string | null
          version: number | null
        }
        Insert: {
          admin_only?: boolean | null
          allowed_end_time?: string | null
          allowed_start_time?: string | null
          category?: string | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: number
          is_active?: boolean | null
          justification_deadline_hours?: number | null
          name: string
          skip_justifications?: boolean | null
          tenant_id?: string | null
          updated_at?: string | null
          version?: number | null
        }
        Update: {
          admin_only?: boolean | null
          allowed_end_time?: string | null
          allowed_start_time?: string | null
          category?: string | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          id?: number
          is_active?: boolean | null
          justification_deadline_hours?: number | null
          name?: string
          skip_justifications?: boolean | null
          tenant_id?: string | null
          updated_at?: string | null
          version?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "checklist_templates_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_templates_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      checklists: {
        Row: {
          accuracy: number | null
          completed_at: string | null
          created_at: string | null
          created_by: string | null
          id: number
          latitude: number | null
          local_id: string | null
          longitude: number | null
          sector_id: number | null
          started_at: string | null
          status: string | null
          store_id: number
          sync_status: string | null
          template_id: number
          tenant_id: string | null
          updated_at: string | null
          validated_at: string | null
          validated_by: string | null
        }
        Insert: {
          accuracy?: number | null
          completed_at?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: number
          latitude?: number | null
          local_id?: string | null
          longitude?: number | null
          sector_id?: number | null
          started_at?: string | null
          status?: string | null
          store_id: number
          sync_status?: string | null
          template_id: number
          tenant_id?: string | null
          updated_at?: string | null
          validated_at?: string | null
          validated_by?: string | null
        }
        Update: {
          accuracy?: number | null
          completed_at?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: number
          latitude?: number | null
          local_id?: string | null
          longitude?: number | null
          sector_id?: number | null
          started_at?: string | null
          status?: string | null
          store_id?: number
          sync_status?: string | null
          template_id?: number
          tenant_id?: string | null
          updated_at?: string | null
          validated_at?: string | null
          validated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checklists_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "checklist_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_validated_by_fkey"
            columns: ["validated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      cross_validations: {
        Row: {
          aprendiz_checklist_id: number | null
          created_at: string | null
          diferenca: number | null
          estoquista_checklist_id: number | null
          id: number
          is_primary: boolean | null
          linked_validation_id: number | null
          match_reason: string | null
          numero_nota: string
          sector_id: number | null
          status: string | null
          store_id: number
          tenant_id: string | null
          validated_at: string | null
          valor_aprendiz: number | null
          valor_estoquista: number | null
        }
        Insert: {
          aprendiz_checklist_id?: number | null
          created_at?: string | null
          diferenca?: number | null
          estoquista_checklist_id?: number | null
          id?: number
          is_primary?: boolean | null
          linked_validation_id?: number | null
          match_reason?: string | null
          numero_nota: string
          sector_id?: number | null
          status?: string | null
          store_id: number
          tenant_id?: string | null
          validated_at?: string | null
          valor_aprendiz?: number | null
          valor_estoquista?: number | null
        }
        Update: {
          aprendiz_checklist_id?: number | null
          created_at?: string | null
          diferenca?: number | null
          estoquista_checklist_id?: number | null
          id?: number
          is_primary?: boolean | null
          linked_validation_id?: number | null
          match_reason?: string | null
          numero_nota?: string
          sector_id?: number | null
          status?: string | null
          store_id?: number
          tenant_id?: string | null
          validated_at?: string | null
          valor_aprendiz?: number | null
          valor_estoquista?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "cross_validations_aprendiz_checklist_id_fkey"
            columns: ["aprendiz_checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cross_validations_estoquista_checklist_id_fkey"
            columns: ["estoquista_checklist_id"]
            isOneToOne: false
            referencedRelation: "checklists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cross_validations_linked_validation_id_fkey"
            columns: ["linked_validation_id"]
            isOneToOne: false
            referencedRelation: "cross_validations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cross_validations_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cross_validations_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cross_validations_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      field_conditions: {
        Row: {
          condition_type: string
          condition_value: Json
          created_at: string | null
          deadline_days: number
          default_assignee_id: string | null
          default_function_id: number | null
          description_template: string | null
          field_id: number
          id: number
          is_active: boolean
          severity: string
          tenant_id: string | null
        }
        Insert: {
          condition_type: string
          condition_value: Json
          created_at?: string | null
          deadline_days?: number
          default_assignee_id?: string | null
          default_function_id?: number | null
          description_template?: string | null
          field_id: number
          id?: number
          is_active?: boolean
          severity?: string
          tenant_id?: string | null
        }
        Update: {
          condition_type?: string
          condition_value?: Json
          created_at?: string | null
          deadline_days?: number
          default_assignee_id?: string | null
          default_function_id?: number | null
          description_template?: string | null
          field_id?: number
          id?: number
          is_active?: boolean
          severity?: string
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "field_conditions_default_assignee_id_fkey"
            columns: ["default_assignee_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "field_conditions_default_function_id_fkey"
            columns: ["default_function_id"]
            isOneToOne: false
            referencedRelation: "functions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "field_conditions_field_id_fkey"
            columns: ["field_id"]
            isOneToOne: false
            referencedRelation: "template_fields"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "field_conditions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      functions: {
        Row: {
          color: string | null
          created_at: string | null
          description: string | null
          icon: string | null
          id: number
          is_active: boolean | null
          name: string
          teams_webhook_url: string | null
          tenant_id: string | null
        }
        Insert: {
          color?: string | null
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: number
          is_active?: boolean | null
          name: string
          teams_webhook_url?: string | null
          tenant_id?: string | null
        }
        Update: {
          color?: string | null
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: number
          is_active?: boolean | null
          name?: string
          teams_webhook_url?: string | null
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "functions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      invites: {
        Row: {
          accepted_at: string | null
          created_at: string | null
          email: string
          expires_at: string | null
          id: string
          invited_by: string
          role: string
          tenant_id: string
          token: string | null
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string | null
          email: string
          expires_at?: string | null
          id?: string
          invited_by: string
          role?: string
          tenant_id: string
          token?: string | null
        }
        Update: {
          accepted_at?: string | null
          created_at?: string | null
          email?: string
          expires_at?: string | null
          id?: string
          invited_by?: string
          role?: string
          tenant_id?: string
          token?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invites_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          action_url: string | null
          created_at: string | null
          id: number
          is_read: boolean
          link: string | null
          message: string | null
          metadata: Json | null
          tenant_id: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          action_url?: string | null
          created_at?: string | null
          id?: number
          is_read?: boolean
          link?: string | null
          message?: string | null
          metadata?: Json | null
          tenant_id?: string | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          action_url?: string | null
          created_at?: string | null
          id?: number
          is_read?: boolean
          link?: string | null
          message?: string | null
          metadata?: Json | null
          tenant_id?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_members: {
        Row: {
          accepted_at: string | null
          created_at: string | null
          id: string
          invite_token: string | null
          invited_by: string | null
          invited_email: string | null
          organization_id: string
          role: string
          user_id: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string | null
          id?: string
          invite_token?: string | null
          invited_by?: string | null
          invited_email?: string | null
          organization_id: string
          role?: string
          user_id: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string | null
          id?: string
          invite_token?: string | null
          invited_by?: string | null
          invited_email?: string | null
          organization_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          business_info: Json | null
          cancel_at_period_end: boolean | null
          created_at: string | null
          current_period_end: string | null
          features: string[] | null
          id: string
          is_active: boolean | null
          max_stores: number | null
          max_users: number | null
          name: string
          pending_plan: string | null
          plan: string
          previous_plan: string | null
          settings: Json | null
          slug: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          trial_ends_at: string | null
          updated_at: string | null
        }
        Insert: {
          business_info?: Json | null
          cancel_at_period_end?: boolean | null
          created_at?: string | null
          current_period_end?: string | null
          features?: string[] | null
          id?: string
          is_active?: boolean | null
          max_stores?: number | null
          max_users?: number | null
          name: string
          pending_plan?: string | null
          plan?: string
          previous_plan?: string | null
          settings?: Json | null
          slug: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          trial_ends_at?: string | null
          updated_at?: string | null
        }
        Update: {
          business_info?: Json | null
          cancel_at_period_end?: boolean | null
          created_at?: string | null
          current_period_end?: string | null
          features?: string[] | null
          id?: string
          is_active?: boolean | null
          max_stores?: number | null
          max_users?: number | null
          name?: string
          pending_plan?: string | null
          plan?: string
          previous_plan?: string | null
          settings?: Json | null
          slug?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          trial_ends_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      pricing_configs: {
        Row: {
          features: string[]
          id: string
          is_active: boolean
          max_stores: number
          max_users: number
          name: string
          price_brl: number
          sort_order: number
          stripe_price_id: string | null
          updated_at: string | null
        }
        Insert: {
          features?: string[]
          id: string
          is_active?: boolean
          max_stores?: number
          max_users?: number
          name: string
          price_brl?: number
          sort_order?: number
          stripe_price_id?: string | null
          updated_at?: string | null
        }
        Update: {
          features?: string[]
          id?: string
          is_active?: boolean
          max_stores?: number
          max_users?: number
          name?: string
          price_brl?: number
          sort_order?: number
          stripe_price_id?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      sectors: {
        Row: {
          color: string | null
          created_at: string | null
          description: string | null
          icon: string | null
          id: number
          is_active: boolean | null
          name: string
          store_id: number
          tenant_id: string | null
        }
        Insert: {
          color?: string | null
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: number
          is_active?: boolean | null
          name: string
          store_id: number
          tenant_id?: string | null
        }
        Update: {
          color?: string | null
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: number
          is_active?: boolean | null
          name?: string
          store_id?: number
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sectors_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sectors_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      store_managers: {
        Row: {
          assigned_at: string | null
          assigned_by: string | null
          can_manage_users: boolean | null
          can_view_all_checklists: boolean | null
          can_view_reports: boolean | null
          id: number
          store_id: number
          tenant_id: string | null
          user_id: string
        }
        Insert: {
          assigned_at?: string | null
          assigned_by?: string | null
          can_manage_users?: boolean | null
          can_view_all_checklists?: boolean | null
          can_view_reports?: boolean | null
          id?: number
          store_id: number
          tenant_id?: string | null
          user_id: string
        }
        Update: {
          assigned_at?: string | null
          assigned_by?: string | null
          can_manage_users?: boolean | null
          can_view_all_checklists?: boolean | null
          can_view_reports?: boolean | null
          id?: number
          store_id?: number
          tenant_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "store_managers_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "store_managers_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "store_managers_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "store_managers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      stores: {
        Row: {
          address: string | null
          cnpj: string | null
          created_at: string | null
          id: number
          is_active: boolean | null
          latitude: number | null
          longitude: number | null
          name: string
          require_gps: boolean
          tenant_id: string | null
        }
        Insert: {
          address?: string | null
          cnpj?: string | null
          created_at?: string | null
          id?: number
          is_active?: boolean | null
          latitude?: number | null
          longitude?: number | null
          name: string
          require_gps?: boolean
          tenant_id?: string | null
        }
        Update: {
          address?: string | null
          cnpj?: string | null
          created_at?: string | null
          id?: number
          is_active?: boolean | null
          latitude?: number | null
          longitude?: number | null
          name?: string
          require_gps?: boolean
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "stores_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      template_fields: {
        Row: {
          calculation: Json | null
          field_type: string
          help_text: string | null
          id: number
          is_required: boolean | null
          name: string
          options: Json | null
          placeholder: string | null
          section_id: number | null
          sort_order: number | null
          template_id: number
          tenant_id: string | null
          validation: Json | null
        }
        Insert: {
          calculation?: Json | null
          field_type: string
          help_text?: string | null
          id?: number
          is_required?: boolean | null
          name: string
          options?: Json | null
          placeholder?: string | null
          section_id?: number | null
          sort_order?: number | null
          template_id: number
          tenant_id?: string | null
          validation?: Json | null
        }
        Update: {
          calculation?: Json | null
          field_type?: string
          help_text?: string | null
          id?: number
          is_required?: boolean | null
          name?: string
          options?: Json | null
          placeholder?: string | null
          section_id?: number | null
          sort_order?: number | null
          template_id?: number
          tenant_id?: string | null
          validation?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "template_fields_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "template_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_fields_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "checklist_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_fields_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      template_sections: {
        Row: {
          description: string | null
          id: number
          name: string
          sort_order: number
          template_id: number
          tenant_id: string | null
        }
        Insert: {
          description?: string | null
          id?: number
          name: string
          sort_order?: number
          template_id: number
          tenant_id?: string | null
        }
        Update: {
          description?: string | null
          id?: number
          name?: string
          sort_order?: number
          template_id?: number
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "template_sections_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "checklist_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_sections_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      template_visibility: {
        Row: {
          assigned_at: string | null
          assigned_by: string | null
          function_id: number | null
          id: number
          roles: string[] | null
          sector_id: number | null
          store_id: number
          template_id: number
          tenant_id: string | null
        }
        Insert: {
          assigned_at?: string | null
          assigned_by?: string | null
          function_id?: number | null
          id?: number
          roles?: string[] | null
          sector_id?: number | null
          store_id: number
          template_id: number
          tenant_id?: string | null
        }
        Update: {
          assigned_at?: string | null
          assigned_by?: string | null
          function_id?: number | null
          id?: number
          roles?: string[] | null
          sector_id?: number | null
          store_id?: number
          template_id?: number
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "template_visibility_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_visibility_function_id_fkey"
            columns: ["function_id"]
            isOneToOne: false
            referencedRelation: "functions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_visibility_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_visibility_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_visibility_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "checklist_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "template_visibility_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_integrations: {
        Row: {
          created_at: string | null
          credentials: Json
          id: string
          is_active: boolean | null
          last_sync_at: string | null
          provider: string
          store_id: number | null
          sync_error: string | null
          tenant_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          credentials?: Json
          id?: string
          is_active?: boolean | null
          last_sync_at?: string | null
          provider: string
          store_id?: number | null
          sync_error?: string | null
          tenant_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          credentials?: Json
          id?: string
          is_active?: boolean | null
          last_sync_at?: string | null
          provider?: string
          store_id?: number | null
          sync_error?: string | null
          tenant_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tenant_integrations_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tenant_integrations_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      user_sectors: {
        Row: {
          assigned_at: string | null
          assigned_by: string | null
          id: number
          role: string
          sector_id: number
          tenant_id: string | null
          user_id: string
        }
        Insert: {
          assigned_at?: string | null
          assigned_by?: string | null
          id?: number
          role?: string
          sector_id: number
          tenant_id?: string | null
          user_id: string
        }
        Update: {
          assigned_at?: string | null
          assigned_by?: string | null
          id?: number
          role?: string
          sector_id?: number
          tenant_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_sectors_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_sectors_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_sectors_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_sectors_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_store_roles: {
        Row: {
          assigned_at: string | null
          assigned_by: string | null
          id: number
          role: string
          store_id: number
          tenant_id: string | null
          user_id: string
        }
        Insert: {
          assigned_at?: string | null
          assigned_by?: string | null
          id?: number
          role: string
          store_id: number
          tenant_id?: string | null
          user_id: string
        }
        Update: {
          assigned_at?: string | null
          assigned_by?: string | null
          id?: number
          role?: string
          store_id?: number
          tenant_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_store_roles_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_store_roles_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_store_roles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_store_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_stores: {
        Row: {
          created_at: string | null
          id: number
          is_primary: boolean | null
          sector_id: number | null
          store_id: number
          tenant_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: number
          is_primary?: boolean | null
          sector_id?: number | null
          store_id: number
          tenant_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: number
          is_primary?: boolean | null
          sector_id?: number | null
          store_id?: number
          tenant_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_stores_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_stores_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_stores_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_stores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          email: string
          full_name: string
          function_id: number | null
          id: string
          is_active: boolean | null
          is_admin: boolean | null
          is_manager: boolean | null
          is_tech: boolean | null
          phone: string | null
          sector_id: number | null
          store_id: number | null
          tenant_id: string | null
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          email: string
          full_name: string
          function_id?: number | null
          id: string
          is_active?: boolean | null
          is_admin?: boolean | null
          is_manager?: boolean | null
          is_tech?: boolean | null
          phone?: string | null
          sector_id?: number | null
          store_id?: number | null
          tenant_id?: string | null
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string
          full_name?: string
          function_id?: number | null
          id?: string
          is_active?: boolean | null
          is_admin?: boolean | null
          is_manager?: boolean | null
          is_tech?: boolean | null
          phone?: string | null
          sector_id?: number | null
          store_id?: number | null
          tenant_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "users_function_id_fkey"
            columns: ["function_id"]
            isOneToOne: false
            referencedRelation: "functions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "users_sector_id_fkey"
            columns: ["sector_id"]
            isOneToOne: false
            referencedRelation: "sectors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "users_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "users_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      mv_compliance_summary: {
        Row: {
          compliance_rate: number | null
          non_conformities: number | null
          store_id: number | null
          template_id: number | null
          tenant_id: string | null
          total_responses: number | null
          week: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checklists_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "checklist_templates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      mv_daily_kpis: {
        Row: {
          completed: number | null
          in_progress: number | null
          plans_created: number | null
          plans_resolved: number | null
          report_date: string | null
          store_id: number | null
          tenant_id: string | null
          total_checklists: number | null
        }
        Relationships: [
          {
            foreignKeyName: "checklists_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklists_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      get_compliance_summary: {
        Args: { p_from: string; p_tenant_id: string; p_to: string }
        Returns: {
          compliance_rate: number
          non_conformities: number
          store_id: number
          template_id: number
          tenant_id: string
          total_responses: number
          week: string
        }[]
      }
      get_current_org_id: { Args: never; Returns: string }
      get_current_role: { Args: never; Returns: string }
      get_daily_kpis: {
        Args: { p_from: string; p_tenant_id: string; p_to: string }
        Returns: {
          completed: number
          in_progress: number
          plans_created: number
          plans_resolved: number
          report_date: string
          store_id: number
          tenant_id: string
          total_checklists: number
        }[]
      }
      get_my_tenant_id: { Args: never; Returns: string }
      get_org_billing: {
        Args: { p_org_id: string }
        Returns: {
          cancel_at_period_end: boolean
          current_period_end: string
          current_stores: number
          current_users: number
          features: string[]
          id: string
          max_stores: number
          max_users: number
          name: string
          pending_plan: string
          plan: string
          previous_plan: string
          stripe_customer_id: string
          stripe_subscription_id: string
          trial_ends_at: string
        }[]
      }
      has_role: { Args: { required_role: string }; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      is_store_manager: { Args: { check_store_id: number }; Returns: boolean }
      refresh_materialized_views: { Args: never; Returns: undefined }
      user_function_id: { Args: never; Returns: number }
      user_is_manager: { Args: never; Returns: boolean }
      user_managed_store_ids: { Args: never; Returns: number[] }
      user_sector_id: { Args: never; Returns: number }
      user_sector_ids: { Args: never; Returns: number[] }
      user_store_id: { Args: never; Returns: number }
      user_store_ids: { Args: never; Returns: number[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

